# Generated by Django 4.1.7 on 2023-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project\\image')),
                ('github', models.CharField(blank=True, max_length=256, null=True)),
                ('demo', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
